travis:
  secure:
    BINSTAR_TOKEN: O7+wLuLkPzfUuJCdkcH/qineMWGxs/e5wi//1N+BYff6sqp0J9kRl8Ri5Gv2SMlTr+e28P5QW2h34mOAHekY8rtwCobhajhX8kf4f6ukLUx3pXq+c4VxrHq3VJCYPbBbHaUzj0Ud88v5zlEuNX55PiQIPUEqjHTKPRcdHpc9KUBjvcRaUBbJB1680E4SVog3UpuQQWInzhv7j9qGL/zzi/AitOBGv6SmruA0MnRG2NSUd+avj9VhOCGr47TR/kAVgRv6wdgqdhxOgGD2+2w3RjM21aQh8b1x0ylgJu5iUvZ9+r0+ZFqz2X88e0MP3duib41pr0jhccWVkSMy2nyXEdom3k4iGmcsi7DSmtfeHlUiOQOwS1piA0OOsMTEocbm8Zq8GNgNOeqFVoDT9Uo8tXqZN2f1TBC/OgLX5WaroNf9Dbu9IIu9vM83Fzr5jJoJhdELn+xkMPlazrqb7wVqj3ThsMBq1d6QpoEbi7s1c3yqse5bsNhzVV10YWDEeuMEcZ38/XAKeEG1UX7uqyK86LJ8GLLWSkkCE/Fo/8L61cHK+qFDC4KZScWHkgEg5OdV3C21bnfSth0WOgb/Kw9mkB4ZqToI68ivy4WFxG0VyLJ/sJl123+L7D1kKiSzTdWuH0p3H0Fwfde0IsrkAW2oZgkgQNlcEbYw7NBIC0Nw9Bs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
